//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eloadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eloadas()
        {
            this.Foglalas = new HashSet<Foglalas>();
        }
    
        public int EloadasID { get; set; }
        public byte FilmFK { get; set; }
        public short TeremFK { get; set; }
        public byte EloadastipusFK { get; set; }
        public string IdoSav { get; set; }
        public System.DateTime Datum { get; set; }
        public string Nap { get; set; }
        public string Szinkron { get; set; }
        public string Felirat { get; set; }
    
        public virtual Eloadastipus Eloadastipus { get; set; }
        public virtual Film Film { get; set; }
        public virtual Terem Terem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foglalas> Foglalas { get; set; }
    }
}
