//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaFlixEntities : DbContext
    {
        public CinemaFlixEntities()
            : base("name=CinemaFlixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eloadas> Eloadas { get; set; }
        public virtual DbSet<Eloadastipus> Eloadastipus { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Mozi> Mozi { get; set; }
        public virtual DbSet<Szemely> Szemely { get; set; }
        public virtual DbSet<Terem> Terem { get; set; }
        public virtual DbSet<Foglalas> Foglalas { get; set; }
    }
}
