//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szemely
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szemely()
        {
            this.Foglalas = new HashSet<Foglalas>();
        }
    
        public int SzemelyID { get; set; }
        public string Nev { get; set; }
        public string Email { get; set; }
        public decimal Telefonszam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foglalas> Foglalas { get; set; }
    }
}
